# Regenerates `nix/guest/kernel.config`, the .config that
# `nix/guest/kernel.nix` feeds to the kernel build.
#
#     nix build .#kernel-config
#     cp result nix/guest/kernel.config
#
# The output is byte-identical to the committed file, so `diff result
# nix/guest/kernel.config` is a valid check that the two have not drifted.
#
# Why a derivation and not the host `make ARCH=riscv defconfig` the task
# brief suggests: kconfig is not just text munging. Symbols such as
# TOOLCHAIN_HAS_ZBB and AS_HAS_INSN are resolved by *running* the target
# compiler and assembler, so the config is only correct if it is generated
# with the same toolchain that will later compile the kernel. Running it
# here, from the same `crossPkgs` that nix/guest/kernel.nix uses, makes that
# true by construction — and it does not require a Linux kernel tree to
# bootstrap its host tools on macOS, which it cannot reliably do.
#
# This builds on `${crossPkgs.buildPackages.system}`, so from a Darwin
# checkout it needs the Linux builder:
#
#     nix build .#kernel-config --builders \
#       'ssh-ng://linux-builder aarch64-linux /etc/nix/builder_ed25519 4 1 kvm,benchmark,big-parallel - -'
{ crossPkgs }:
let
  inherit (crossPkgs) lib;
  # Same attribute nix/guest/kernel.nix builds, so `src` and the toolchain
  # cannot drift between the config and the kernel that consumes it.
  kernel = crossPkgs.linuxKernel.kernels.linux_6_12;
  native = crossPkgs.buildPackages;
in
native.stdenv.mkDerivation {
  pname = "guest-kernel-config";
  inherit (kernel) version src;

  nativeBuildInputs = [
    native.bison
    native.flex
    native.perl
    native.bc
  ];

  fragment = ./kernel.fragment;

  # `commonMakeFlags` is the exact CC/LD/ARCH/CROSS_COMPILE set that
  # `linuxKernel.manualConfig` will use for the real build (it comes from
  # the kernel derivation's own passthru), which is what keeps the
  # toolchain-probing symbols honest.
  kernelMakeFlags = kernel.commonMakeFlags;

  dontConfigure = true;

  postPatch = ''
    patchShebangs scripts
  '';

  buildPhase = ''
    runHook preBuild

    make $kernelMakeFlags O=build defconfig

    # -m merges the fragment textually without invoking kconfig, so nothing
    # is re-derived until the explicit olddefconfig below.
    bash scripts/kconfig/merge_config.sh -m -O build build/.config "$fragment"
    make $kernelMakeFlags O=build olddefconfig

    # olddefconfig will happily drop an option whose dependencies were also
    # disabled, and a dropped CONFIG_RISCV_SBI_V01 turns `earlycon=sbi` into
    # a silent no-op — an early boot failure with no output at all. Fail
    # the build instead.
    fail=0
    while IFS= read -r line; do
      case "$line" in
        CONFIG_*=*)
          sym=''${line%%=*}
          if ! grep -qxF "$line" build/.config; then
            echo "kernel.fragment: requested '$line' but final .config has:" >&2
            grep -E "^(# )?$sym[ =]" build/.config >&2 || echo "  <symbol absent>" >&2
            fail=1
          fi
          ;;
        "# CONFIG_"*" is not set")
          sym=''${line#'# '}
          sym=''${sym%' is not set'}
          # An absent symbol is as disabled as an explicit "is not set":
          # turning off a parent menu removes the child from the file
          # entirely. Only an enabled value is a failure.
          if grep -qE "^$sym=" build/.config; then
            echo "kernel.fragment: requested '$line' but final .config has:" >&2
            grep -E "^$sym=" build/.config >&2
            fail=1
          fi
          ;;
      esac
    done < "$fragment"
    if [ "$fail" -ne 0 ]; then
      echo "generated .config does not honour nix/guest/kernel.fragment" >&2
      exit 1
    fi

    # BLOCK=n with BLK_DEV_INITRD=y is the one combination in the fragment
    # that looks like a mistake, so assert it explicitly rather than leaving
    # a reader to trust the loop above: an initramfs is a cpio unpacked into
    # rootfs and never touches the block layer.
    grep -qxF '# CONFIG_BLOCK is not set' build/.config
    grep -qxF 'CONFIG_BLK_DEV_INITRD=y' build/.config

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    {
      # ASCII only: this banner is prepended to a kernel .config, which the
      # kconfig tools read as plain ASCII.
      echo "# Generated by \`nix build .#kernel-config\` -- do not edit by hand."
      echo "# linux ${kernel.version} \`make ARCH=riscv defconfig\`, then"
      echo "# nix/guest/kernel.fragment merged in and olddefconfig'd."
      echo "# Every override in that fragment is verified present here."
      cat build/.config
    } > $out
    runHook postInstall
  '';

  meta = {
    description = "Kconfig .config for the rv64 emulator's guest kernel";
    platforms = lib.platforms.linux;
  };
}
